server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.fenzx.Config.MysqlConfig

  datasource:
    #    url: jdbc:mysql://localhost:3306/fenzx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #    username: fenzxAdmin
    #    password: freeKerman
    url: jdbc:mysql://101.200.61.6:3306/fenzx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fenzxAdmin
    password: freeKerman
#    https://blog.csdn.net/darkread/article/details/89562148  这是有用的
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
