server:
  port: 8080

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: com.fenzx.Config.MysqlConfig

  datasource:
    url: jdbc:mysql://localhost:3306/fenzx?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: fenzxAdmin
    password: freeKerman
    driver-class-name: com.mysql.cj.jdbc.Driver


